server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/resqora_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: sanjeev
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 153638514241-l636habkio0verl6opkp4oab23pedhe3.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

jwt:
  secret: UmVzcW9yYVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5Rm9yTG9jYWxEZXZlbG9wbWVudDIwMjY=
  expiration: 86400000

twilio:
  account:
    sid: YOUR_TWILIO_SID
  auth:
    token: YOUR_TWILIO_TOKEN
  phone:
    number: YOUR_TWILIO_NUMBER

sendgrid:
  api-key: YOUR_SENDGRID_KEY
  from-email: sanjeevraj952545@gmail.com